### ISSUE TITLE
Bulk Inventory update not working

### ISSUE THREAD

**Issue by smgom** [fillup/walmart-partner-api-sdk-php#1]
I am trying with this 

```
$feed = $client->bulk([
    'InventoryHeader' => [
        'version' => '1.4',
    ],
    'inventory' => [
        [
            'sku' => 'XXXXX',
            'quantity' => [
                'unit' => 'EACH',
                'amount' => 5,
            ],
            'fulfillmentLagTime' => 3,
        ],
        [
            'sku' => 'XXXXX',
            'quantity' => [
                'unit' => 'EACH',
                'amount' => 9,
            ],
            'fulfillmentLagTime' => 1,
        ]
    ],
        ]);
```

Its giving me response 200 , But when I am checking feed status, Its returning ERROR.

**Comment by fillup** [comment]
When you check feed status do you have any more details about the error?

**Comment by smgom** [comment]
No, It just show error. Also the xml created does not maches. I am using
php5.6 can this be issue?

**Comment by fillup** [comment]
I don't think PHP version should be a problem for you. What is not matching about the XML?

**Comment by smgom** [comment]
<inventory>is comming twice in xml

**Comment by fillup** [comment]
So based on the PHP example you have above, what is the generated XML?

**Comment by smgom** [comment]
On bulk update it's working fine,returning status 200 and feedID. But in feeds I'm having feedStatus as Error. Can you explain why?

And I'm getting no more details regarding the error.

**Comment by fillup** [comment]
I believe the update requests are processed with minimal validation and then processed in a queue. So the first 200 response means the request was valid from a request/format perspective, but the feed status error must mean there is a problem when trying to process the request. Can you email me the feedId and I can ask the responsible team to check into it on the backend to see if they can get any further information? My email is my first dot last at gmail dot com.

**Comment by smgom** [comment]
Yeah I'll send you the feed id's.

**Comment by fillup** [comment]
@smgom I think I found the problem, I believe it is with my documentation missing the wrapping element for the call. So your example above should look like:

``` php
$feed = $client->bulk([
    'InventoryFeed' => [
        'InventoryHeader' => [
            'version' => '1.4',
        ],
        'inventory' => [
            [
                'sku' => 'XXXXX',
                'quantity' => [
                    'unit' => 'EACH',
                    'amount' => 5,
                ],
                'fulfillmentLagTime' => 3,
            ],
            [
                'sku' => 'XXXXX',
                'quantity' => [
                    'unit' => 'EACH',
                    'amount' => 9,
                ],
                'fulfillmentLagTime' => 1,
            ]
        ],
    ]
]);
```

Note the new parent `InventoryFeed` element. Can you try that and let me know if you still have errors?

**Comment by smgom** [comment]
@fillup Hi, thanks it's working now,I'm getting status "INPROGRESS",but I had added multiple items to update but the feed is showing [itemsReceived] => 1.

**Comment by fillup** [comment]
Which method/API are you using to get the status? Are you using get() or getFeedItem()

**Comment by smgom** [comment]
I'm using get().

**Comment by smgom** [comment]
Hi @fillup ,

Using getFeedItem():
`Array
(
    [statusCode] => 200
    [meta] => Array
        (
            [feedId] => XXXXXXXXXXXXXXXXXXXX
            [feedStatus] => INPROGRESS
            [ingestionErrors] => Array
                (
                )

```
        [itemsReceived] => 1
        [itemsSucceeded] => 0
        [itemsFailed] => 0
        [itemsProcessing] => 1
        [limit] => 50
        [totalCount] => 0
        [nextCursor] => includeDetails=true&limit=50&skuOffset=NULL
    )

[elements] => Array
    (
        [itemDetails] => Array
            (
            )

    )
```

)`

And using get():

`Array
(
    [statusCode] => 200
    [feedId] => XXXXXXXXXXXXXXXXXXXXXX
    [feedStatus] => INPROGRESS
    [ingestionErrors] => Array
        (
        )

```
[itemsReceived] => 1
[itemsSucceeded] => 0
[itemsFailed] => 0
[itemsProcessing] => 1
[offset] => 0
[limit] => 50
[itemDetails] => Array
    (
    )
```

)`

I  had added multiple items. In results you can see itemsReceived onl 1 in both API's.

POST parameters:

`$client->bulk([
    'InventoryFeed' => [
        'InventoryHeader' => [
            'version' => '1.4',
        ],
        'inventory' => [
            [
                'sku' => 'XXXXX',
                'quantity' => [
                    'unit' => 'EACH',
                    'amount' => 5,
                ],
                'fulfillmentLagTime' => 3,
            ],
            [
                'sku' => 'XXXXX',
                'quantity' => [
                    'unit' => 'EACH',
                    'amount' => 9,
                ],
                'fulfillmentLagTime' => 1,
            ],
            [
                'sku' => 'XXXXX',
                'quantity' => [
                    'unit' => 'EACH',
                    'amount' => 9,
                ],
                'fulfillmentLagTime' => 1,
            ]
        ],
    ]
        ]);`

Is there any mistake I'm making?

**Comment by fillup** [comment]
That looks right to me. My test account isn't working right now so I'm not able to do some testing/debugging. When I get my access restored I'll test this out and let you know what I find. If you figure it out in the mean time please let me know what it was.

**Comment by smgom** [comment]
@fillup 
Hey the problem is that 

This is the requested xml by the api 

`<InventoryFeed xmlns="http://walmart.com/">
  <InventoryHeader>
      <version>1.4</version>
  </InventoryHeader>
  <inventory>
      <sku>1068155</sku>
      <quantity>
          <unit>EACH</unit>
          <amount>10</amount>
      </quantity>
      <fulfillmentLagTime>1</fulfillmentLagTime>
  </inventory>
  <inventory>
      <sku>10210321</sku>
      <quantity>
          <unit>EACH</unit>
          <amount>20</amount>
      </quantity>
      <fulfillmentLagTime>3</fulfillmentLagTime>
  </inventory>
</InventoryFeed>`

And we are creating this
`<?xml version="1.0" encoding="UTF-8"?>
<InventoryFeed>
    <InventoryHeader>
        <version>1.4</version>
    </InventoryHeader>
    <inventory>
        <item>
            <sku>MRPP-5809XSBKPK</sku>
            <quantity>
                <unit>EACH</unit>
                <amount>5</amount>
            </quantity>
            <fulfillmentLagTime>3</fulfillmentLagTime>
        </item>
        <item>
            <sku>MRPP-5743XSBKRD</sku>
            <quantity>
                <unit>EACH</unit>
                <amount>9</amount>
            </quantity>
            <fulfillmentLagTime>1</fulfillmentLagTime>
        </item>
    </inventory>
</InventoryFeed>`
So the main problem is we dont need this bigger inventory and instead of item we need inventory

**Comment by smgom** [comment]
`$xml = $a2x->asXml();` this function has the problem.

**Comment by fillup** [comment]
Good find! I'll work on getting this fixed in a few hours, hopefully I'll get it done today.

**Comment by smgom** [comment]
@fillup , Thanks a lot, Can you please resolve it asap, because I am really in need of this. I tried a few things like 
changing A2X.php Line 109 from item to inventory. But could not get the exact one.

**Comment by smgom** [comment]
Or If you could just tell me a quick temporary fix for now.

**Comment by fillup** [comment]
@smgom I believe this should be fixed now. Can you try the code from the `develop` branch here and let me know if that fixes it for you? Make sure you update composer dependencies too because I had to update the array2xml library to support this list type. The XML I am generated now in my test is:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<InventoryFeed>
    <InventoryHeader>
        <version>1.4</version>
    </InventoryHeader>
    <inventory>
        <sku>0987654321</sku>
        <quantity>
            <unit>EACH</unit>
            <amount>5</amount>
        </quantity>
        <fulfillmentLagTime>3</fulfillmentLagTime>
    </inventory>
    <inventory>
        <sku>12345678</sku>
        <quantity>
            <unit>EACH</unit>
            <amount>9</amount>
        </quantity>
        <fulfillmentLagTime>1</fulfillmentLagTime>
    </inventory>
</InventoryFeed>
```

**Comment by smgom** [comment]
Sorry not working again. Actually I am getting one extra     <inventory> tab
`
<?xml version="1.0" encoding="UTF-8"?>
<InventoryFeed>
    <InventoryHeader>
        <version>1.4</version>
    </InventoryHeader>
    <inventory>
    <inventory>
        <sku>0987654321</sku>
        <quantity>
            <unit>EACH</unit>
            <amount>5</amount>
        </quantity>
        <fulfillmentLagTime>3</fulfillmentLagTime>
    </inventory>
    <inventory>
        <sku>12345678</sku>
        <quantity>
            <unit>EACH</unit>
            <amount>9</amount>
        </quantity>
        <fulfillmentLagTime>1</fulfillmentLagTime>
    </inventory>
    </inventory>
</InventoryFeed>
`

**Comment by fillup** [comment]
I fixed Bulk Price and Bulk Items at the same time so they should be working properly. 

Here is an example:

``` php
$update = $client->bulk([
    'PriceFeed' => [
        'PriceHeader' => [
            'version' => '1.5',
        ],
        'Price' => [
            [
                'itemIdentifier' => [
                    'sku' => '1131270'
                ],
                'pricingList' => [
                    'pricing' => [
                        'currentPrice' => [
                            'value' => [
                                'currency' => 'USD',
                                'amount' => '4.00',
                            ],
                        ],
                        'currentPriceType' => 'BASE',
                        'comparisonPrice' => [
                            'value' => [
                                'currency' => 'USD',
                                'amount' => '5.99',
                            ],
                        ],
                        'priceDisplayCode' => [
                            'submapType' => 'CHECKOUT',
                        ],
                        'effectiveDate' => '2016-07-02T12:38:43-04:00',
                        'expirationDate' => '2016-08-02T12:38:43-04:00',
                    ]
                ],
            ],
            [
                'itemIdentifier' => [
                    'sku' => '2435543'
                ],
                'pricingList' => [
                    'pricing' => [
                        'currentPrice' => [
                            'value' => [
                                'currency' => 'USD',
                                'amount' => '4.00',
                            ],
                        ],
                        'currentPriceType' => 'BASE',
                        'comparisonPrice' => [
                            'value' => [
                                'currency' => 'USD',
                                'amount' => '5.99',
                            ],
                        ],
                        'priceDisplayCode' => [
                            'submapType' => 'CHECKOUT',
                        ],
                        'effectiveDate' => '2016-07-02T12:38:43-04:00',
                        'expirationDate' => '2016-08-02T12:38:43-04:00',
                    ]
                ],
            ],
        ],
    ],
]);
```

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<PriceFeed>
    <PriceHeader>
        <version>1.5</version>
    </PriceHeader>
    <Price>
        <itemIdentifier>
            <sku>1131270</sku>
        </itemIdentifier>
        <pricingList>
            <pricing effectiveDate="2016-07-02T12:38:43-04:00" expirationDate="2016-08-02T12:38:43-04:00">
                <currentPrice>
                    <value currency="USD" amount="4.00"></value>
                </currentPrice>
                <currentPriceType>BASE</currentPriceType>
                <comparisonPrice>
                    <value currency="USD" amount="5.99"></value>
                </comparisonPrice>
                <priceDisplayCode submapType="CHECKOUT"></priceDisplayCode>
            </pricing>
        </pricingList>
    </Price>
    <Price>
        <itemIdentifier>
            <sku>2435543</sku>
        </itemIdentifier>
        <pricingList>
            <pricing effectiveDate="2016-07-02T12:38:43-04:00" expirationDate="2016-08-02T12:38:43-04:00">
                <currentPrice>
                    <value currency="USD" amount="4.00"></value>
                </currentPrice>
                <currentPriceType>BASE</currentPriceType>
                <comparisonPrice>
                    <value currency="USD" amount="5.99"></value>
                </comparisonPrice>
                <priceDisplayCode submapType="CHECKOUT"></priceDisplayCode>
            </pricing>
        </pricingList>
    </Price>
</PriceFeed>
```

**Comment by fillup** [comment]
@smgom are you using the develop branch of code? I'm not able to duplicate your inventory issue. Here is what I'm using to test:

``` php
$feed = $client->bulk([
    'InventoryFeed' => [
        'InventoryHeader' => [
            'version' => '1.4',
        ],
        'inventory' => [
            [
                'sku' => '86678GHGHGKL',
                'quantity' => [
                    'unit' => 'EACH',
                    'amount' => 5,
                ],
                'fulfillmentLagTime' => 3,
            ],
            [
                'sku' => '12345678',
                'quantity' => [
                    'unit' => 'EACH',
                    'amount' => 9,
                ],
                'fulfillmentLagTime' => 1,
            ]
        ],
    ]
]);
```

Generates:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<InventoryFeed>
    <InventoryHeader>
        <version>1.4</version>
    </InventoryHeader>
    <inventory>
        <sku>86678GHGHGKL</sku>
        <quantity>
            <unit>EACH</unit>
            <amount>5</amount>
        </quantity>
        <fulfillmentLagTime>3</fulfillmentLagTime>
    </inventory>
    <inventory>
        <sku>12345678</sku>
        <quantity>
            <unit>EACH</unit>
            <amount>9</amount>
        </quantity>
        <fulfillmentLagTime>1</fulfillmentLagTime>
    </inventory>
</InventoryFeed>
```

If your project is including this library via composer be sure to use version `dev-develop` and then then do a `composer update`. After you confirm this is all fixed for you I'll get it merged and released with a version number so you can go back to depending on a stable version.

**Comment by fillup** [comment]
@smgom can you confirm this is fixed for you?

**Comment by smgom** [comment]
Hi @fillup,

This is working. I had tried bulk inventory update and it's updating all products inventory.

Thanks.

**Comment by fillup** [comment]
Thanks for the confirmation. I merged it in, updated version is `1.0.2`.

**Comment by beg123** [comment]
sir i m using c# sendind request for update price in bulk it is giving 401 unautorised error 

and my code is 

string UnixTime = UnixTimeStamp(), Str_Signature = signData(UnixTime), result = string.Empty;
        if (Str_Signature.Contains("Error::-"))
        {
            return Str_Signature;
        }
        HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create("https://marketplace.walmartapis.com/v2/feeds?feedType=price");
        httpWebRequest.Method = "POST";
        httpWebRequest.Accept = "application/xml";
        httpWebRequest.ContentType = "multipart/form-data;";
        httpWebRequest.Headers.Add("WM_SVC.NAME", "Walmart Marketplace");
        httpWebRequest.Headers.Add("WM_CONSUMER.ID", Str_ConsumerID);
        httpWebRequest.Headers.Add("WM_SEC.TIMESTAMP", UnixTime);
        httpWebRequest.Headers.Add("WM_SEC.AUTH_SIGNATURE", Str_Signature);
        httpWebRequest.Headers.Add("WM_QOS.CORRELATION_ID", Guid.NewGuid().ToString());

```
    //Request_Xml = "";
    byte[] bytes;
    bytes = System.Text.Encoding.ASCII.GetBytes(Request_Xml);
    Stream requestStream = httpWebRequest.GetRequestStream();
    requestStream.Write(bytes, 0, bytes.Length);
    requestStream.Close();
    HttpWebResponse response;
    response = (HttpWebResponse)httpWebRequest.GetResponse();
    if (response.StatusCode == HttpStatusCode.OK)
    {
        Stream responseStream = response.GetResponseStream();
        string responseStr = new StreamReader(responseStream).ReadToEnd();
        return responseStr;
    }
```

:- this code work fine with all Get methods

and xml is :-

Request_Xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><PriceFeed xmlns:gmp=\"http://walmart.com/\"><PriceHeader><version>1.5</version></PriceHeader><Price><itemIdentifier><sku>PLE-PFAB60-FWMT</sku></itemIdentifier><pricingList><pricing><currentPrice><value currency=\"USD\" amount=\"44.86\" /></currentPrice></pricing></pricingList></Price><Price><itemIdentifier><sku>PEN-5824306-FWMT</sku></itemIdentifier><pricingList><pricing><currentPrice><value currency=\"USD\" amount=\"133.69\" /></currentPrice></pricing></pricingList></Price></PriceFeed>";

**Comment by beg123** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<PriceFeed xmlns:gmp="http://walmart.com/">
   <PriceHeader>
      <version>1.5</version>
   </PriceHeader>
   <Price>
      <itemIdentifier>
         <sku>PLE-PFAB60-FWMT</sku>
      </itemIdentifier>
      <pricingList>
         <pricing>
            <currentPrice>
               <value currency="USD" amount="44.86" />
            </currentPrice>
         </pricing>
      </pricingList>
   </Price> 
  <Price>
      <itemIdentifier>
         <sku>PEN-5824306-FWMT</sku>
      </itemIdentifier>
      <pricingList>
         <pricing>
            <currentPrice>
               <value currency="USD" amount="133.69" />
            </currentPrice>
        </pricing>
      </pricingList>
   </Price>
</PriceFeed>

**Comment by beg123** [comment]
Request_Xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><PriceFeed xmlns:gmp=\"http://walmart.com/\"><PriceHeader><version>1.5</version></PriceHeader><Price><itemIdentifier><sku>PLE-PFAB60-FWMT</sku></itemIdentifier><pricingList><pricing><currentPrice><value currency=\"USD\" amount=\"44.86\" /></currentPrice></pricing></pricingList></Price><Price><itemIdentifier><sku>PEN-5824306-FWMT</sku></itemIdentifier><pricingList><pricing><currentPrice><value currency=\"USD\" amount=\"133.69\" /></currentPrice></pricing></pricingList></Price></PriceFeed>";

**Comment by fillup** [comment]
@beg123 I don't know C# but I recommend you use https://github.com/chrisvire/walmart-auth-signature-dotnet for calculating your signatures. I know he has some unit tests in place to ensure this calculation method works properly.

**Comment by chrisjr2** [comment]
What worked for me is the following:

Content-Type text/plain
Accept application/xml
Content-Encoding application/text

I then just sent the JSON straight without having a boundary or new line breaks and it worked just fine. I did before have a boundary and kept running into issues (content-type: multipart/form-date; boundary=boundarydoesntworkWALMART). Either a generic system error data error or it returned moreThanOneFeed error.
