### ISSUE TITLE
composer error.

### ISSUE THREAD

**Issue by ghost** [fillup/walmart-partner-api-sdk-php#10]
I'm trying to do a composer update after adding the package to my composer.json.

The error I'm getting is:

Installation request for fillup/walmart-partner-api-sdk-php ^1.0.0 -> sati                                                                               sfiable by fillup/walmart-partner-api-sdk-php[1.0.0, 1.0.1, 1.0.2, 1.0.3].

I'm not sure how to fix this.  Any suggestions?

**Comment by fillup** [comment]
Can you provide the rest of the error output? Sometimes with composer it shows you things that are satisfiable and then errors, so what is the full output?

**Comment by ghost** [comment]
I ran with verbose, that was all that was outputed.

**Comment by ghost** [comment]
Actually, here's more:

 Problem 1
    - fillup/walmart-partner-api-sdk-php 1.0.4 requires guzzlehttp/guzzle-services dev-master -> satisfiable by guzzlehttp/guzzle-services[dev-master] but these conflict with your requirements or minimum-stability.
    - fillup/walmart-partner-api-sdk-php 1.0.3 requires guzzlehttp/guzzle-services dev-master -> satisfiable by guzzlehttp/guzzle-services[dev-master] but these conflict with your requirements or minimum-stability.
    - fillup/walmart-partner-api-sdk-php 1.0.2 requires guzzlehttp/guzzle-services dev-master -> satisfiable by guzzlehttp/guzzle-services[dev-master] but these conflict with your requirements or minimum-stability.
    - fillup/walmart-partner-api-sdk-php 1.0.1 requires guzzlehttp/guzzle-services dev-master -> satisfiable by guzzlehttp/guzzle-services[dev-master] but these conflict with your requirements or minimum-stability.
    - fillup/walmart-partner-api-sdk-php 1.0.0 requires guzzlehttp/guzzle-services dev-master -> satisfiable by guzzlehttp/guzzle-services[dev-master] but these conflict with your requirements or minimum-stability.
    - Installation request for fillup/walmart-partner-api-sdk-php ^1.0.0 -> satisfiable by fillup/walmart-partner-api-sdk-php[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4].

**Comment by fillup** [comment]
Ahh yes, I'm aware of that one. I depend on some fixes that are in the `master` branch of `guzzlehttp/guzzle-services` but they were never released with a version number so composer does not consider them stable. You can work around this though by depending on it directly in your own composer.json file as well (composer is ok with _unstable_ dependencies if you include them yourself, but will reject them if included via dependent libraries). So update the dependencies section of your `composer.json` to look like:

``` json
"fillup/walmart-partner-api-sdk-php": "^1.0.4",
"guzzlehttp/guzzle-services": "dev-master"
```

I should update my docs to include that, thanks for pointing this out.

**Comment by ghost** [comment]
Thanks for the help. That actually solved the main issue. Unfortunately, it revealed another one.  This one appears to be more complicated to solve its relying on a package that doesn't have a release.

 roave/security-advisories

Here's the output:

 Problem 1
    - Installation request for fillup/walmart-partner-api-sdk-php ^1.0.4 -> satisfiable by fillup/walmart-partner-api-sdk-php[1.0.4].
    - fillup/walmart-partner-api-sdk-php 1.0.4 requires roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master] but these conflict with your requirements or minimum-stability.

Thanks

**Comment by fillup** [comment]
Heh, another one of the same situation. `roave/security-advisories` is a nice package that just defines conflicts with packages to have known vulnerabilities. You should add it to your list of dependencies as well. And since it is a list that can change any time it is never "stable" so you just required`dev-master`. 

Perhaps I should not require it myself to not force it on others as well, but it is a good practice so I think everyone should include it.

**Comment by ghost** [comment]
I wouldn't require it in your package and leave that up to the developer to add.

**Comment by ghost** [comment]
That solved the issue, thanks.

**Comment by fillup** [comment]
I moved `roave/security-advisories` in 07e82bd to a suggestion instead of dependency. You should keep it in your list of dependencies, but at least this wont be a blocker if someone really doesn't want it for some reason.
