### ISSUE TITLE
Error in Get all orders filters!

### ISSUE THREAD

**Issue by mdalvi** [fillup/walmart-partner-api-sdk-php#14]
I am trying to pull 10 orders within specified date range with status as Created.

Here is the code:

```
$orders = $client->list([
    'status' => 'Created', // optional
    'createdStartDate' => '2016-09-05', // optional
    'createdEndDate' => '2016-09-20', // optional
    'limit' => 10, // optional, default 10
]);
```

However I get all kind of orders with different orderLineStatus as **Shipped**, **Created** and also **Acknowledged**. Why is the filter for Created only is not being applied?

**Comment by fillup** [comment]
Good question. Can you use something like [Charles Proxy](https://www.charlesproxy.com/) to capture the actual request and response to ensure the SDK formatted the API call properly? If everything looks good there you should report that information to your integration manager at Walmart as they may have a bug or be able to do further investigation.

**Comment by fillup** [comment]
@mdalvi I'm going to close this issue for now, but if you're still having problems go ahead and reopen it.
