### ISSUE TITLE
Pre PHP 5.5 Fix

### ISSUE THREAD

**Issue by cralls** [fillup/walmart-partner-api-sdk-php#17]
Pre PHP 5.5 users will need the following update to support the getIncludeWrappingTag function since boolval doesn't exist pre PHP 5.5:

public function getIncludeWrappingTag($schema, $position)
    {
        /*
         \* Check schema to see if this position should not be included as a wrapping tag
         */
        if (isset($schema[$position]['includeWrappingTag'])) {
            if (!function_exists('boolval')) {
                return (bool) $schema[$position]['includeWrappingTag'];
            } else {
                return boolval($schema[$position]['includeWrappingTag']);
            }
        }

```
    return true;
}
```

**Comment by fillup** [comment]
@cralls this issue was really with the `fillup/array2xml` library. I updated it to just cast the value as opposed to using the boolval() function.
