### ISSUE TITLE
How to get the Total products count?

### ISSUE THREAD

**Issue by jpnathannew** [fillup/walmart-partner-api-sdk-php#20]
Hi, 

I tried to get the total products count using this SDK. When I tried to use the product list. 20 products only returned. I have 50 products right now. So kindly guide me to get the product count.

Thanks,
Nathan

**Comment by fillup** [comment]
According to the documentation there is no meta response element to tell you the total number and you need to just make subsequent calls with higher `offset` values until you no longer get responses:

https://developer.walmartapis.com/#get-all-items
