### ISSUE TITLE
Dependency on guzzlehttp/guzzle-services dev-master

### ISSUE THREAD

**Issue by ajbonner** [fillup/walmart-partner-api-sdk-php#21]
The documentation acknowledges the requirement to pull dev-master for guzzlehttp/guzzle-services.

Obviously this is suboptimal if that project suddenly pushes a bunch of updates (however unlikely given the lack of updates on that project).

Apart from replacing the dependency with a more active one, perhaps update the docs to make users depend on the specific commit you need?

For example in composer json you can pin to a sha1 commit

``` javascript
require: {
    ...
    "guzzlehttp/guzzle-services": "dev-master#8adb1d160b19eeb8320d2f846bc3b8dac8a878a4"
}, 
```

This would make it less likely to cause problems down the road if the project suddenly springs back to life.

**Comment by fillup** [comment]
Sure, that's a fair suggestion. I considered forking and tagging a version so it comes through as stable, but I didn't want to scare people about including a forked version rather than the official. As a user of this library do you have an opinion on that approach?

**Comment by ajbonner** [comment]
I think given your issue https://github.com/guzzle/guzzle-services/issues/110 has not gotten any response, I'd just fork.

Longer term I think it would be good to just replace the dependency with a more active project.

**Comment by fillup** [comment]
Done in version 1.0.9
