### ISSUE TITLE
"Use guzzlehttp/guzzle instead"

### ISSUE THREAD

**Issue by hamiltonnieri8755** [fillup/walmart-partner-api-sdk-php#26]
Hi

I downloaded the repo and copied it to xampp/htdocs. 

And executed "composer install". 

It returns "Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.". 

Any idea, @fillup @vanhoavn @simoheinonen ?

**Comment by simoheinonen** [comment]
See https://github.com/fillup/walmart-partner-api-sdk-php/issues/7#issuecomment-244391968

After https://github.com/guzzle/guzzle-services/pull/109 has been merged it would be possible to get rid of that message

**Comment by hamiltonnieri8755** [comment]
Please let me know what to do on my end. Can you explain more details about the solution?

**Comment by hamiltonnieri8755** [comment]
OK, it works, thanks.
