### ISSUE TITLE
Feed not working

### ISSUE THREAD

**Issue by hamiltonnieri8755** [fillup/walmart-partner-api-sdk-php#27]
Hi

*****************************************************************
use Walmart\Feed;

$client = new Feed([
'consumerId' => 'XXX',
'privateKey' => 'XXX'
]);

$feed = $client->list([
    'feedId' => 'C96A9D44FE8B4934B877222DBD8101FF@AQMBAAA', // required
    'limit' => 50, // optional, default 50
    'offset' => 0, // optional, default 0
]);
*****************************************************************

Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error response [url] https://marketplace.walmartapis.com/v2/feeds?feedId=C96A9D44FE8B4934B877222DBD8101FF%40AQMBAAA&limit=50&offset=0 [status code] 401 [reason phrase] Unauthorized' in C:\xampp\htdocs\walmartpartnerapi\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php:89 Stack trace: #0 C:\xampp\htdocs\walmartpartnerapi\vendor\guzzlehttp\guzzle\src\Subscriber\HttpError.php(33): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\R.......

When I remove "@" from the feed ID, it shows 

"Array ( [statusCode] => 200 [totalResults] => 0 [offset] => 0 [limit] => 50 [results] => Array ( ) )"

No error in this case. 

What is wrong here?

Thanks.

@fillup @vanhoavn @simoheinonen

**Comment by hamiltonnieri8755** [comment]
Figured it out. Thanks.

**Comment by nikoanzai** [comment]
@hamiltonnieri8755 What was the solution?
