### ISSUE TITLE
How do I add more attributes to the item feed

### ISSUE THREAD

**Issue by hamiltonnieri8755** [fillup/walmart-partner-api-sdk-php#28]
Hi @fillup @vanhoavn @simoheinonen 

As what I see the usage doc, it only supports "product name", "sku", "product id", "main image", "long/shelf/short description" and something like that. 

I would like to add some more attributes and item options like color/size. 

How can I add them to feed?

Thanks.

**Comment by jpnathannew** [comment]
Hi @fillup @vanhoavn @simoheinonen

Hope you are doing well. I am also tried to create configurable product from Item feed api call. But when I pass more attributes. Its through the error only.

Please suggest me.

Thanks,
Nathan

**Comment by fillup** [comment]
Those are good questions, I haven't tried that before. Are you structuring the data based on the schemas? The library for serializing the array of data into XML was one I developed for this SDK and its also possible that the structure at some point in there does something I'm not accounting for. Can you provide me with some more examples?

**Comment by jpnathannew** [comment]
Hi @fillup , 

Actually total first level categories 25 . Each and every category have a separate type of required fields. I found the all the category schema XSD files from following URL

[https://developer.walmartapis.com/files/mp/WalmartMarketplaceXSDs-2.1.8.zip](url)

Each category have different variation options details - [http://marketplace.walmart.com/knowledgebase/articles/Article/Supported-Variant-Attribute-Names?q=variations&c=&l=en_US&kb=](url)

For Set Up A Variant Group please refer the following URL. That url have sample xml format request also.
[http://marketplace.walmart.com/knowledgebase/articles/Article/How-To-Set-Up-A-Variant-Group?q=variations&c=&l=en_US&kb=](url)
