### ISSUE TITLE
Regards orders fetching count

### ISSUE THREAD

**Issue by Rohi145** [fillup/walmart-partner-api-sdk-php#38]
Hello ,

Now order fetching default count is 10 .Can i increase this count?

**Comment by sandip5678** [comment]
Default is **10**.
Limit value cannot be larger than **200**

**Comment by Rohi145** [comment]
so can I Set this limit value greater than 10?,Now if  I passed this value greater than 10 then getting error.

**Comment by fillup** [comment]
Thanks @sandybrainer for responding
