### ISSUE TITLE
deprecation of developer.walmartapis.com

### ISSUE THREAD

**Issue by wiiiimm** [fillup/walmart-partner-api-sdk-php#44]
> This site is being deprecated and will be removed on March 31, 2017. Please use the enhanced Developer Portal API site at: https://developer.walmart.com.

Over at developer.walmartapis.com, the document is pointing to a much more primitive version of the "enhanced Developer Portal API" at developer.walmart.com. The new site contains a much more basic set of UI and only the Feed APIs are listed there with things like items related APIs missing (https://developer.walmartapis.com/#overview). Do you think these APIs are also being deprecated or is it just the documentation site?

**Comment by kushan85** [comment]
The new documentation is this one https://developer.walmart.com/#/apicenter/marketPlace

**Comment by wiiiimm** [comment]
thanks @kushan85
