### ISSUE TITLE
Upgrade to Guzzle 6

### ISSUE THREAD

**Issue by simoheinonen** [fillup/walmart-partner-api-sdk-php#7]
A bit tricky though since this library heavily relies on `guzzlehttp/guzzle-services` which doesn't support Guzzle 6 yet. Hopefully it will though: https://github.com/guzzle/guzzle-services/issues/89#issuecomment-242912296

**Comment by fillup** [comment]
It's nice to see someone working on updating guzzle-services for Guzzle 6. If/when it gets merged into the main guzzle-services repo I'll look into what it will take to update this library. Let me know when that happens if you don't see me already working on it.
